version: "3.8"
services:
  ecommerce-app:
    build: .
    ports:
      - 5555:5555
    environment:
      SPRING_APPLICATION_JSON: '{
        "server.port": 5555,
        "spring.datasource.url": "jdbc:postgresql://postgresdb:5432/comm",
        "spring.datasource.username": "root",
        "spring.datasource.password": "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    depends_on:
      postgresdb:
        condition: service_healthy
    networks:
      - ecommerce-Apis-network

  postgresdb:
    image: postgres:latest
    container_name: postgresdb
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=comm
    ports:
      - '5432:5432'
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "comm", "-U", "root"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ecommerce-Apis-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgresdb
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '8081:80'
    networks:
      - ecommerce-Apis-network

volumes:
  pg-data:

networks:
  ecommerce-Apis-network:
